Repository Kiki1875b/sb04-ootdboo-team7, pull requests merged in 2025-07, with the labels that each got.

#67 [FEATURE] ClothesService 추가 작업
  src/main/java/com/example/ootd/domain/clothes/controller/ClothesController.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesSearchCondition.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesSearchRequest.java
  src/main/java/com/example/ootd/domain/clothes/entity/Clothes.java
  src/main/java/com/example/ootd/domain/clothes/entity/ClothesAttribute.java
  src/main/java/com/example/ootd/domain/clothes/mapper/ClothesMapper.java
  src/main/java/com/example/ootd/domain/clothes/repository/ClothesRepository.java
  src/main/java/com/example/ootd/domain/clothes/repository/CustomClothesRepository.java
  src/main/java/com/example/ootd/domain/clothes/repository/impl/CustomAttributeRepositoryImpl.java
  src/main/java/com/example/ootd/domain/clothes/repository/impl/CustomClothesRepositoryImpl.java
  src/main/java/com/example/ootd/domain/clothes/service/ClothesService.java
  src/main/java/com/example/ootd/domain/clothes/service/RecommendService.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/ClothesServiceImpl.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/RecommendServiceImpl.java
  src/main/java/com/example/ootd/domain/image/entity/Image.java
  src/main/java/com/example/ootd/domain/image/event/ImageDeleteListner.java
  src/main/java/com/example/ootd/domain/image/service/impl/S3ServiceImpl.java
  src/main/java/com/example/ootd/exception/ErrorCode.java
  src/main/java/com/example/ootd/exception/GlobalExceptionHandler.java
  src/main/java/com/example/ootd/exception/clothes/AttributeDetailNotFoundException.java
Labels: FEATURE✈️

#74 [FEATURE] : 배치 작업 생성
  src/main/java/com/example/ootd/OotdApplication.java
  src/main/java/com/example/ootd/batch/RegionCsvReader.java
  src/main/java/com/example/ootd/batch/RegionInfo.java
  src/main/java/com/example/ootd/batch/RegionPartitioner.java
  src/main/java/com/example/ootd/batch/WeatherApiEntityMapper.java
  src/main/java/com/example/ootd/batch/WeatherBatchController.java
  src/main/java/com/example/ootd/batch/WeatherBatchData.java
  src/main/java/com/example/ootd/batch/WeatherBatchNotificationService.java
  src/main/java/com/example/ootd/batch/WeatherJobConfig.java
  src/main/java/com/example/ootd/batch/WeatherProcessor.java
  src/main/java/com/example/ootd/batch/WeatherScheduler.java
  src/main/java/com/example/ootd/batch/WeatherWriter.java
  src/main/java/com/example/ootd/batch/dto/RegionInfo.java
  src/main/java/com/example/ootd/batch/dto/WeatherBatchData.java
  src/main/java/com/example/ootd/batch/job/RegionPartitioner.java
  src/main/java/com/example/ootd/batch/job/WeatherProcessor.java
  src/main/java/com/example/ootd/batch/job/WeatherReader.java
  src/main/java/com/example/ootd/batch/job/WeatherWriter.java
  src/main/java/com/example/ootd/batch/listener/WeatherBatchFailureListener.java
  src/main/java/com/example/ootd/batch/listener/WeatherItemListener.java
  src/main/java/com/example/ootd/batch/listener/WeatherJobExecutionListener.java
  src/main/java/com/example/ootd/batch/listener/WeatherStepExecutionListener.java
  src/main/java/com/example/ootd/batch/mapper/WeatherApiEntityMapper.java
  src/main/java/com/example/ootd/config/AsyncConfig.java
  src/main/java/com/example/ootd/domain/weather/entity/Humidity.java
  src/main/java/com/example/ootd/domain/weather/entity/Precipitation.java
  src/main/java/com/example/ootd/domain/weather/entity/Temperature.java
  src/main/java/com/example/ootd/domain/weather/entity/WindSpeed.java
  src/main/resources/application.yml
  src/main/resources/regions.csv
Labels: FEATURE✈️

#77 [Refactor] : Batch writer 청크단위로 DB에 저장
  src/main/java/com/example/ootd/batch/job/WeatherWriter.java
  src/main/java/com/example/ootd/batch/mapper/WeatherApiEntityMapper.java
  src/main/java/com/example/ootd/domain/weather/api/WeatherApiClient.java
  src/main/resources/application.yml
Labels: REFACTOR⭐️

#96 [FEATURE] : 안 좋은 날씨 알림
  src/main/java/com/example/ootd/batch/WeatherJobConfig.java
  src/main/java/com/example/ootd/batch/job/WeatherReader.java
  src/main/java/com/example/ootd/batch/listener/WeatherAlertListener.java
  src/main/java/com/example/ootd/batch/listener/WeatherItemListener.java
  src/main/java/com/example/ootd/domain/location/api/KakaoApiClient.java
  src/main/java/com/example/ootd/domain/location/service/LocationServiceImpl.java
  src/main/java/com/example/ootd/domain/user/repository/UserRepository.java
  src/main/java/com/example/ootd/domain/weather/WeatherController.java
Labels: FEATURE✈️

#108 [REFACTOR] : weather 예외 처리 수정
  src/main/java/com/example/ootd/batch/listener/WeatherAlertListener.java
  src/main/java/com/example/ootd/batch/listener/WeatherAlertType.java
  src/main/java/com/example/ootd/domain/location/api/KakaoApiClient.java
  src/main/java/com/example/ootd/domain/location/repository/LocationRepository.java
  src/main/java/com/example/ootd/domain/location/service/LocationServiceImpl.java
  src/main/java/com/example/ootd/domain/weather/api/WeatherApiClient.java
  src/main/java/com/example/ootd/domain/weather/service/WeatherServiceImpl.java
  src/main/java/com/example/ootd/exception/ErrorCode.java
  src/main/java/com/example/ootd/exception/GlobalExceptionHandler.java
  src/main/java/com/example/ootd/exception/location/LocationApiException.java
  src/main/java/com/example/ootd/exception/location/LocationCoordinateOutOfRangeException.java
  src/main/java/com/example/ootd/exception/location/LocationException.java
  src/main/java/com/example/ootd/exception/location/LocationNotFoundException.java
  src/main/java/com/example/ootd/exception/location/LocationRegionInfoInsufficientException.java
  src/main/java/com/example/ootd/exception/weather/InvalidCoordinatesException.java
  src/main/java/com/example/ootd/exception/weather/WeatherApiException.java
  src/main/java/com/example/ootd/exception/weather/WeatherDataInsufficientException.java
  src/main/java/com/example/ootd/exception/weather/WeatherNotFoundException.java
Labels: REFACTOR⭐️

#112 [FEATURE] monitoring 구현 및 배포
  INFRA_TROUBLESHOOTING.md
  build.gradle
  docker-compose.yml
  monitoring/prometheus.yml
  src/main/java/com/example/ootd/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: FEATURE✈️

#125 [TEST] : location weather batch processor 테스트 코드 추가
  src/main/java/com/example/ootd/batch/dto/WeatherBatchData.java
  src/main/java/com/example/ootd/converter/StringListConverter.java
  src/main/java/com/example/ootd/domain/weather/service/WeatherServiceImpl.java
  src/test/java/com/example/ootd/batch/WeatherCleanupSchedulerTest.java
  src/test/java/com/example/ootd/batch/WeatherSchedulerTest.java
  src/test/java/com/example/ootd/batch/job/WeatherProcessorTest.java
  src/test/java/com/example/ootd/config/TestConfig.java
  src/test/java/com/example/ootd/converter/StringListConverterTest.java
  src/test/java/com/example/ootd/domain/location/api/KakaoApiClientTest.java
  src/test/java/com/example/ootd/domain/location/mapper/WeatherLocationMapperTest.java
  src/test/java/com/example/ootd/domain/location/repository/LocationRepositoryTest.java
  src/test/java/com/example/ootd/domain/location/service/LocationServiceImplTest.java
  src/test/java/com/example/ootd/domain/location/util/GridGpsConverterTest.java
  src/test/java/com/example/ootd/domain/weather/WeatherControllerTest.java
  src/test/java/com/example/ootd/domain/weather/WeatherLocationIntegrationTest.java
  src/test/java/com/example/ootd/domain/weather/api/WeatherApiClientTest.java
  src/test/java/com/example/ootd/domain/weather/mapper/WeatherMapperTest.java
  src/test/java/com/example/ootd/domain/weather/repository/WeatherRepositoryTest.java
  src/test/java/com/example/ootd/domain/weather/service/WeatherServiceImplTest.java
Labels: TEST🧪

#138 [TEST] ClothesRepositoryTest 작성
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesAttributeSearchCondition.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesSearchCondition.java
  src/main/java/com/example/ootd/domain/clothes/repository/custom/impl/CustomAttributeRepositoryImpl.java
  src/main/java/com/example/ootd/domain/clothes/repository/custom/impl/CustomClothesRepositoryImpl.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/AttributeServiceImpl.java
  src/main/java/com/example/ootd/domain/feed/repository/custom/impl/CustomFeedCommentRepositoryImpl.java
  src/main/java/com/example/ootd/domain/feed/repository/custom/impl/CustomFeedRepositoryImpl.java
  src/main/java/com/example/ootd/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/example/ootd/domain/notification/dto/NotificationRequest.java
  src/test/java/com/example/ootd/TestEntityFactory.java
  src/test/java/com/example/ootd/domain/clothes/repository/AttributeRepositoryTest.java
  src/test/java/com/example/ootd/domain/clothes/repository/ClothesRepositoryImplTest.java
  src/test/java/com/example/ootd/domain/image/service/ImageServiceImplTest.java
  src/test/resources/application-test.yml
Labels: TEST🧪

#140 [TEST] : 배치 관련 테스트 코드
  src/main/java/com/example/ootd/domain/user/service/AdminInitializationService.java
  src/test/java/com/example/ootd/batch/job/WeatherReaderTest.java
  src/test/java/com/example/ootd/batch/listener/WeatherJobExecutionListenerTest.java
  src/test/java/com/example/ootd/batch/listener/WeatherStepExecutionListenerTest.java
Labels: TEST🧪

#141 [TEST] ClothesService, AttributeService 테스트 작성
  src/main/java/com/example/ootd/domain/clothes/repository/AttributeRepository.java
  src/main/java/com/example/ootd/domain/clothes/repository/custom/impl/CustomAttributeRepositoryImpl.java
  src/main/java/com/example/ootd/domain/clothes/repository/custom/impl/CustomClothesRepositoryImpl.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/AttributeServiceImpl.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/ClothesServiceImpl.java
  src/main/java/com/example/ootd/exception/ErrorCode.java
  src/main/java/com/example/ootd/exception/GlobalExceptionHandler.java
  src/main/java/com/example/ootd/exception/clothes/AttributeNameAlreadyExistsException.java
  src/main/java/com/example/ootd/exception/user/UserException.java
  src/main/java/com/example/ootd/exception/user/UserIdNotFoundException.java
  src/test/java/com/example/ootd/TestEntityFactory.java
  src/test/java/com/example/ootd/domain/clothes/repository/AttributeRepositoryTest.java
  src/test/java/com/example/ootd/domain/clothes/repository/ClothesRepositoryImplTest.java
  src/test/java/com/example/ootd/domain/clothes/service/AttributeServiceImplTest.java
  src/test/java/com/example/ootd/domain/clothes/service/ClothesServiceImplTest.java
  src/test/java/com/example/ootd/domain/image/service/ImageServiceImplTest.java
Labels: TEST🧪

#142 [REFACTORING] 의상 추천 리팩토링
  .github/workflows/workflow.yml
  src/main/java/com/example/ootd/domain/clothes/repository/AttributeRepository.java
  src/main/java/com/example/ootd/domain/clothes/repository/RecommendQueryRepository.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/ClothesServiceImpl.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/RecommendServiceImpl.java
  src/main/java/com/example/ootd/domain/follow/controller/FollowController.java
  src/main/java/com/example/ootd/domain/follow/service/impl/FollowServiceImpl.java
  src/main/java/com/example/ootd/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/ootd/domain/recommend/dto/RecommendationDto.java
  src/main/java/com/example/ootd/domain/recommend/dto/ScoredClothesDto.java
  src/main/java/com/example/ootd/domain/recommend/repository/RecommendQueryRepository.java
  src/main/java/com/example/ootd/domain/recommend/service/ClothesCalculator.java
  src/main/java/com/example/ootd/domain/recommend/service/ClothesSelector.java
  src/main/java/com/example/ootd/domain/recommend/service/RecommendService.java
  src/main/java/com/example/ootd/domain/recommend/service/impl/RecommendServiceImpl.java
  src/test/java/com/example/ootd/domain/follow/controller/FollowControllerTest.java
  src/test/java/com/example/ootd/domain/follow/repository/FollowRepositoryCustomTest.java
  src/test/java/com/example/ootd/domain/follow/repository/FollowRepositoryTest.java
  src/test/java/com/example/ootd/domain/follow/service/FollowServiceImplTest.java
  src/test/java/com/example/ootd/domain/recommend/repository/RecommendQueryRepositoryTest.java
  src/test/java/com/example/ootd/domain/user/UserServiceImplTest.java
  src/test/java/com/example/ootd/security/SecurityIntegrationTest.java
  src/test/resources/logback-test.xml
Labels: REFACTOR⭐️

#146 [REFACTOR] : 배치 캐시 로직 변경
  src/main/java/com/example/ootd/batch/listener/WeatherAlertListener.java
  src/main/java/com/example/ootd/batch/service/WeatherAlertService.java
  src/main/java/com/example/ootd/config/CacheConfig.java
  src/main/resources/application.yml
Labels: REFACTOR⭐️

#150 [TEST] Clothes, Feed 관련 테스트 코드 작성
  src/main/java/com/example/ootd/OotdApplication.java
  src/main/java/com/example/ootd/config/JpaConfig.java
  src/main/java/com/example/ootd/domain/feed/dto/request/FeedCommentSearchCondition.java
  src/main/java/com/example/ootd/domain/feed/dto/request/FeedSearchCondition.java
  src/main/java/com/example/ootd/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/example/ootd/exception/weather/WeatherNotFoundException.java
  src/test/java/com/example/ootd/TestPrincipalUser.java
  src/test/java/com/example/ootd/domain/clothes/controller/AttributeControllerTest.java
  src/test/java/com/example/ootd/domain/clothes/controller/ClothesControllerTest.java
  src/test/java/com/example/ootd/domain/clothes/service/ClothesServiceImplTest.java
  src/test/java/com/example/ootd/domain/feed/service/FeedServiceImplTest.java
Labels: TEST🧪

#151 [REFACTOR] 의상 추천 고도화, 테스트 코드 작성
  .github/workflows/workflow.yml
  src/main/java/com/example/ootd/domain/follow/repository/custom/impl/FollowRepositoryCustomImpl.java
  src/main/java/com/example/ootd/domain/recommend/dto/RecommendClothesDto.java
  src/main/java/com/example/ootd/domain/recommend/dto/RecommendationDto.java
  src/main/java/com/example/ootd/domain/recommend/dto/ScoredClothesDto.java
  src/main/java/com/example/ootd/domain/recommend/repository/RecommendQueryRepository.java
  src/main/java/com/example/ootd/domain/recommend/service/ClothesCalculator.java
  src/main/java/com/example/ootd/domain/recommend/service/ClothesSelector.java
  src/main/java/com/example/ootd/domain/recommend/service/impl/RecommendServiceImpl.java
  src/main/java/com/example/ootd/security/Provider.class
  src/main/java/com/example/ootd/security/jwt/BlackList.class
  src/test/java/com/example/ootd/domain/recommend/controller/RecommendControllerTest.java
  src/test/java/com/example/ootd/domain/recommend/repository/RecommendQueryRepositoryTest.java
  src/test/java/com/example/ootd/domain/recommend/service/ClothesCalculatorTest.java
  src/test/java/com/example/ootd/domain/recommend/service/ClothesSelectorTest.java
  src/test/java/com/example/ootd/domain/recommend/service/RecommendServiceImplTest.java
Labels: REFACTOR⭐️

#157 [FIX] follow 수정
  src/main/java/com/example/ootd/domain/follow/dto/FollowSummaryDto.java
  src/main/java/com/example/ootd/domain/follow/repository/FollowRepository.java
  src/main/java/com/example/ootd/domain/follow/service/impl/FollowServiceImpl.java
  src/main/java/com/example/ootd/domain/recommend/service/ClothesSelector.java
Labels: FIX👀

#161 [TEST] Feed 테스트 작성
  src/main/java/com/example/ootd/domain/clothes/service/impl/ClothesServiceImpl.java
  src/main/java/com/example/ootd/domain/feed/repository/custom/CustomFeedCommentRepository.java
  src/main/java/com/example/ootd/domain/feed/repository/custom/impl/CustomFeedCommentRepositoryImpl.java
  src/main/java/com/example/ootd/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/example/ootd/exception/ErrorCode.java
  src/main/java/com/example/ootd/exception/GlobalExceptionHandler.java
  src/main/java/com/example/ootd/exception/user/UserIdNotFoundException.java
  src/main/java/com/example/ootd/exception/user/UserNotFoundException.java
  src/test/java/com/example/ootd/TestEntityFactory.java
  src/test/java/com/example/ootd/domain/clothes/repository/AttributeRepositoryTest.java
  src/test/java/com/example/ootd/domain/clothes/repository/ClothesRepositoryImplTest.java
  src/test/java/com/example/ootd/domain/clothes/service/ClothesServiceImplTest.java
  src/test/java/com/example/ootd/domain/feed/controller/FeedControllerTest.java
  src/test/java/com/example/ootd/domain/feed/repository/FeedCommentRepositoryTest.java
  src/test/java/com/example/ootd/domain/feed/repository/FeedLikeRepositoryTest.java
  src/test/java/com/example/ootd/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/com/example/ootd/domain/feed/service/FeedServiceImplTest.java
Labels: TEST🧪

#168 [FEATURE] : swagger 생성 및 redis 설정
  src/main/java/com/example/ootd/config/SecurityConfig.java
  src/main/java/com/example/ootd/config/api/SwaggerConfig.java
  src/main/java/com/example/ootd/config/api/WeatherApi.java
  src/main/java/com/example/ootd/domain/location/dto/WeatherAPILocation.java
  src/main/java/com/example/ootd/domain/weather/WeatherController.java
  src/main/java/com/example/ootd/domain/weather/dto/HumidityDto.java
  src/main/java/com/example/ootd/domain/weather/dto/PrecipitationDto.java
  src/main/java/com/example/ootd/domain/weather/dto/TemperatureDto.java
  src/main/java/com/example/ootd/domain/weather/dto/WeatherDto.java
  src/main/java/com/example/ootd/domain/weather/dto/WeatherSummaryDto.java
  src/main/java/com/example/ootd/domain/weather/dto/WindSpeedDto.java
  src/main/resources/application.yml
Labels: CHORE📕

#174 [CHORE] 의상 swagger 작성
  src/main/java/com/example/ootd/config/SecurityConfig.java
  src/main/java/com/example/ootd/config/api/AttributeApi.java
  src/main/java/com/example/ootd/config/api/ClothesApi.java
  src/main/java/com/example/ootd/config/api/dto/AttributePageResponse.java
  src/main/java/com/example/ootd/config/api/dto/ClothesPageResponse.java
  src/main/java/com/example/ootd/domain/clothes/controller/AttributeController.java
  src/main/java/com/example/ootd/domain/clothes/controller/ClothesController.java
  src/main/java/com/example/ootd/domain/clothes/dto/data/ClothesAttributeDefDto.java
  src/main/java/com/example/ootd/domain/clothes/dto/data/ClothesAttributeDto.java
  src/main/java/com/example/ootd/domain/clothes/dto/data/ClothesAttributeWithDefDto.java
  src/main/java/com/example/ootd/domain/clothes/dto/data/ClothesDto.java
  src/main/java/com/example/ootd/domain/clothes/dto/data/OotdDto.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesAttributeDefCreateRequest.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesAttributeDefUpdateRequest.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesAttributeSearchCondition.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesCreateRequest.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesSearchCondition.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesUpdateRequest.java
Labels: CHORE📕

#177 [CHORE] 피드 swagger 작성
  src/main/java/com/example/ootd/config/api/FeedApi.java
  src/main/java/com/example/ootd/config/api/dto/CommentPageResponse.java
  src/main/java/com/example/ootd/config/api/dto/FeedPageResponse.java
  src/main/java/com/example/ootd/domain/feed/controller/FeedController.java
  src/main/java/com/example/ootd/domain/feed/dto/data/AuthorDto.java
  src/main/java/com/example/ootd/domain/feed/dto/data/CommentDto.java
  src/main/java/com/example/ootd/domain/feed/dto/data/FeedDto.java
  src/main/java/com/example/ootd/domain/feed/dto/request/CommentCreateRequest.java
  src/main/java/com/example/ootd/domain/feed/dto/request/FeedCommentSearchCondition.java
  src/main/java/com/example/ootd/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/example/ootd/domain/feed/dto/request/FeedSearchCondition.java
  src/main/java/com/example/ootd/domain/feed/dto/request/FeedUpdateRequest.java
Labels: CHORE📕

#179 [FEATURE] 댓글 캐시 적용
  src/main/java/com/example/ootd/domain/feed/dto/request/FeedCommentSearchCondition.java
  src/main/java/com/example/ootd/domain/feed/dto/request/FeedSearchCondition.java
  src/main/java/com/example/ootd/domain/feed/mapper/FeedMapper.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedCommentCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedLikeCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/impl/FeedServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/example/ootd/domain/feed/service/FeedServiceImplTest.java
Labels: FEATURE✈️

#180 [REFACTOR] 의상 추천 LLM 연결 및 캐싱
  build.gradle
  src/main/java/com/example/ootd/config/AsyncConfig.java
  src/main/java/com/example/ootd/config/CacheConfig.java
  src/main/java/com/example/ootd/domain/clothes/repository/ClothesRepository.java
  src/main/java/com/example/ootd/domain/llm/dto/request/ChatRequest.java
  src/main/java/com/example/ootd/domain/llm/dto/response/ChatResponse.java
  src/main/java/com/example/ootd/domain/llm/service/AIRecommendService.java
  src/main/java/com/example/ootd/domain/llm/service/ClothesSimplifier.java
  src/main/java/com/example/ootd/domain/llm/service/OpenAIService.java
  src/main/java/com/example/ootd/domain/llm/service/RecommendationPreloadService.java
  src/main/java/com/example/ootd/domain/recommend/controller/RecommendController.java
  src/main/java/com/example/ootd/domain/recommend/dto/RecommendationDto.java
  src/main/java/com/example/ootd/domain/weather/repository/WeatherRepository.java
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: REFACTOR⭐️

#187 [FIX] 배치 수정
  src/main/java/com/example/ootd/domain/llm/service/AIRecommendService.java
  src/main/java/com/example/ootd/domain/llm/service/RecommendationPreloadService.java
  src/main/java/com/example/ootd/domain/notification/service/impli/NotificationEventConsumer.java
  src/main/java/com/example/ootd/domain/weather/repository/WeatherRepository.java
  src/main/java/com/example/ootd/exception/ErrorCode.java
  src/main/java/com/example/ootd/exception/GlobalExceptionHandler.java
  src/main/java/com/example/ootd/exception/user/UserIdNotFoundException.java
  src/main/java/com/example/ootd/security/jwt/BlackList.java
Labels: FIX👀

#186 [FEATURE] 피드 캐시 적용
  src/main/java/com/example/ootd/config/CacheConfig.java
  src/main/java/com/example/ootd/domain/feed/config/FeedStatesStartupRunner.java
  src/main/java/com/example/ootd/domain/feed/dto/data/FeedCountDto.java
  src/main/java/com/example/ootd/domain/feed/dto/data/FeedSetStatesDto.java
  src/main/java/com/example/ootd/domain/feed/entity/Feed.java
  src/main/java/com/example/ootd/domain/feed/mapper/FeedMapper.java
  src/main/java/com/example/ootd/domain/feed/repository/FeedLikeRepository.java
  src/main/java/com/example/ootd/domain/feed/repository/FeedRepository.java
  src/main/java/com/example/ootd/domain/feed/repository/custom/CustomFeedRepository.java
  src/main/java/com/example/ootd/domain/feed/repository/custom/impl/CustomFeedRepositoryImpl.java
  src/main/java/com/example/ootd/domain/feed/scheduler/FeedScheduler.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedCommentCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedLikeCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/impl/FeedServiceImpl.java
  src/test/java/com/example/ootd/domain/feed/service/FeedServiceImplTest.java
Labels: FEATURE✈️

#191 [FEATURE] Clothes 캐시 추가 및 테스트 추가
  src/main/java/com/example/ootd/domain/clothes/dto/data/ClothesAttributeDefDto.java
  src/main/java/com/example/ootd/domain/clothes/dto/data/ClothesDto.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesAttributeSearchCondition.java
  src/main/java/com/example/ootd/domain/clothes/dto/request/ClothesSearchCondition.java
  src/main/java/com/example/ootd/domain/clothes/mapper/ClothesMapper.java
  src/main/java/com/example/ootd/domain/clothes/repository/AttributeRepository.java
  src/main/java/com/example/ootd/domain/clothes/repository/ClothesAttributeRepository.java
  src/main/java/com/example/ootd/domain/clothes/repository/custom/CustomClothesRepository.java
  src/main/java/com/example/ootd/domain/clothes/repository/custom/impl/CustomClothesRepositoryImpl.java
  src/main/java/com/example/ootd/domain/clothes/service/cache/AttributeCacheService.java
  src/main/java/com/example/ootd/domain/clothes/service/cache/ClothesCacheService.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/AttributeServiceImpl.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/ClothesServiceImpl.java
  src/main/java/com/example/ootd/domain/feed/mapper/FeedMapper.java
  src/main/java/com/example/ootd/domain/feed/repository/custom/impl/CustomFeedRepositoryImpl.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedCommentCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/impl/FeedServiceImpl.java
  src/test/java/com/example/ootd/TestEntityFactory.java
  src/test/java/com/example/ootd/domain/clothes/controller/AttributeControllerTest.java
  src/test/java/com/example/ootd/domain/clothes/controller/ClothesControllerTest.java
  src/test/java/com/example/ootd/domain/clothes/repository/AttributeRepositoryTest.java
  src/test/java/com/example/ootd/domain/clothes/repository/ClothesRepositoryTest.java
  src/test/java/com/example/ootd/domain/clothes/service/AttributeServiceImplTest.java
  src/test/java/com/example/ootd/domain/clothes/service/ClothesServiceImplTest.java
  src/test/java/com/example/ootd/domain/clothes/service/cache/AttributeCacheServiceTest.java
  src/test/java/com/example/ootd/domain/clothes/service/cache/ClothesCacheServiceTest.java
  src/test/java/com/example/ootd/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/com/example/ootd/domain/feed/service/cache/FeedCacheServiceTest.java
  src/test/java/com/example/ootd/domain/feed/service/cache/FeedCommentCacheServiceTest.java
  src/test/java/com/example/ootd/domain/feed/service/cache/FeedLikeCacheServiceTest.java
Labels: TEST🧪

#196 [Fix] task 수정
  ecs-task-definition.json
Labels: FIX👀

#194 [FEATURE] feed, clothes 도메인 캐시 ttl 적용
  src/main/java/com/example/ootd/config/CacheConfig.java
  src/main/java/com/example/ootd/domain/clothes/service/cache/ClothesCacheService.java
  src/main/java/com/example/ootd/domain/clothes/service/impl/AttributeServiceImpl.java
  src/main/java/com/example/ootd/domain/feed/service/cache/FeedCacheService.java
  src/main/java/com/example/ootd/domain/feed/service/impl/FeedServiceImpl.java
  src/main/resources/static/assets/index-umUnbKVT.js
  src/test/java/com/example/ootd/domain/clothes/service/AttributeServiceImplTest.java
  src/test/java/com/example/ootd/domain/feed/service/cache/FeedCacheServiceTest.java
Labels: FEATURE✈️

#198 [FIX] url 통해 의상 불러오기 오류 해결
  src/main/java/com/example/ootd/domain/clothes/service/ClothesInfoLoadService.java
  src/main/java/com/example/ootd/domain/user/controller/UserController.java
Labels: FIX👀
